### ISSUE TITLE
Error while building  opencl

### ISSUE THREAD

**Issue by leiserfg** [not-an-aardvark/lucky-commit#11] opened 2021-07-09 21:12 UTC
I get an error while the building the opencl part:
```
Caused by:
  failed to run custom build command for `lucky_commit v2.0.3`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installvpn5z7/release/build/lucky_commit-3a80f631e28bf5b0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 

  ###################### OPENCL PROGRAM BUILD DEBUG OUTPUT ######################

  <kernel>:18:12: error: __kernel function cannot have argument whose type is, or contains, type size_t
      size_t num_dynamic_blocks,
             ^
  <kernel>:58:9: error: subscripted access is not allowed for OpenCL vectors
          padding_block_ending[0],
          ^                    ~
  <kernel>:108:17: error: subscripted access is not allowed for OpenCL vectors
      uint w0_t = w[0];
                  ^ ~
      
      .....
      
```

**Comment by not-an-aardvark** [comment] 2021-07-09 23:04
Thanks for reporting. I'm going to close this as a duplicate of #10.

I just published v2.0.4 of the package, which includes the fix for that bug. Feel free to open another issue if you encounter any problems with the new version.

**Closed by not-an-aardvark** 2021-07-09 23:04 UTC
