### ISSUE TITLE
OpenCL compile error on cargo install

### ISSUE THREAD

**Issue by lfdominguez** [not-an-aardvark/lucky-commit#12] opened 2021-07-09 22:48 UTC
Hi when execute `cargo install lucky_commit` at the compile .cl file step i have this error:

```
stringInput.cl:18:12: error: 'size_t' (aka 'unsigned int') cannot be used as the type of a kernel parameter
/usr/lib/beignet/include/ocl_types.h:48:33: note: 'size_t' (aka 'unsigned int') declared here
```

**Comment by not-an-aardvark** [comment] 2021-07-09 23:03
Thanks for reporting. I'm going to close this as a duplicate of https://github.com/not-an-aardvark/lucky-commit/issues/10#issuecomment-876912254.

I just published v2.0.4 of the package, which includes the fix for that bug. Feel free to open another issue if you encounter any problems with the new version.

**Closed by not-an-aardvark** 2021-07-09 23:03 UTC
